services:
  - type: web
    name: gemini_back_clone
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn gemini_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,gemini-back-clone.onrender.com,gemini-backend.onrender.com,gemini-backend-clone.onrender.com"
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: gemini-backend-postgres
          property: connectionString
      - key: REDIS_URL
        value: redis://default:AcqKAAIjcDE4MDExMmFhNGU0NmRmYmM5Njk0Yzc4NzUwNTcyYXAxMA@true-quagga-51850.upstash.io:6379
      - key: CELERY_BROKER_URL
        value: redis://default:AcqKAAIjcDE4MDExMmFhNGU0NmRmYmM5Njk0Yzc4NzUwNTcyYXAxMA@true-quagga-51850.upstash.io:6379
      - key: CELERY_RESULT_BACKEND
        value: redis://default:AcqKAAIjcDE4MDExMmFhNGU0NmRmYmM5Njk0Yzc4NzUwNTcyYXAxMA@true-quagga-51850.upstash.io:6379
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: true

  - type: worker
    name: gemini-backend-celery
    env: python
    buildCommand: bash build.sh
    startCommand: celery -A gemini_backend worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: gemini-backend-postgres
          property: connectionString
      - key: REDIS_URL
        value: rediss://default:AcqKAAIjcDE4MDU2MWExMmFhNGU0NmRmYmM5Njk0Yzc4NzUwNTcyYXAxMA@true-quagga-51850.upstash.io:6379
      - key: CELERY_BROKER_URL
        value: rediss://default:AcqKAAIjcDE4MDU2MWExMmFhNGU0NmRmYmM5Njk0Yzc4NzUwNTcyYXAxMA@true-quagga-51850.upstash.io:6379
      - key: CELERY_RESULT_BACKEND
        value: rediss://default:AcqKAAIjcDE4MDU2MWExMmFhNGU0NmRmYmM5Njk0Yzc4NzUwNTcyYXAxMA@true-quagga-51850.upstash.io:6379
      - key: GEMINI_API_KEY
        sync: false

  - type: pserv
    name: gemini-backend-postgres
    env: postgresql
    plan: free

  - type: redis
    name: gemini-backend-redis
    ipAllowList: [] 